/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qooport.modulos.pc;

import comunes.Accion;
import java.awt.Color;
import java.lang.management.ManagementFactory;
import qooport.asociado.Asociado;
import qooport.gui.personalizado.PanelMonitorCarga;
import qooport.utilidades.HiloAccion;
import qooport.utilidades.Util;

/**
 *
 * @author aigarcia
 */
public class MonitorSistemaAsociado extends javax.swing.JFrame {

    private PanelMonitorCarga graficoCPU;
    private PanelMonitorCarga graficoRAM;

    private HiloAccion cargaCPU;
    private HiloAccion cargaRAM;
    private Asociado asociado;

    /**
     * Creates new form MonitorSystema
     */
    public MonitorSistemaAsociado(Asociado asociado) {
        initComponents();
        this.asociado = asociado;

//
        configurarMonitorCPU();
        configurarMonitorRAM();

        btnIniciar.setIcon(Util.cargarIcono16("/resources/start.png"));

        this.setIconImage(Util.cargarIcono16("/resources/monitor_load.png").getImage());

    }

    public void agregarDatoCPU(double sistema, double cpu) {
        graficoCPU.agregarDato(0, sistema);//system load
        graficoCPU.agregarDato(1, cpu);//cpu load
        graficoCPU.repaint();
        jLabel3.setText("Proceso Java=" + Util.redondear(sistema, 2) + "%  CPU=" + Util.redondear(cpu, 2) + "%");
    }

    public void agregarDatoRAM(double libre, double ram) {
        double ocupado = ram - libre;//tamanio ram - ram libre
        //cambia el valor maximo al maximo de ram del asociado
        graficoRAM.setValorMayor(ram);

        graficoRAM.agregarDato(ocupado);
        graficoRAM.repaint();
        jLabel4.setText("RAM=" + Util.convertirBytes(ram) + " Libre=" + Util.convertirBytes(libre) + " Ocupado=" + Util.convertirBytes(ocupado));
    }

    private void configurarMonitorCPU() {
        graficoCPU = new PanelMonitorCarga(300, 50);
        graficoCPU.setOpaque(true); //content panes must be opaque
        graficoCPU.iniciarSeries(2);
        graficoCPU.setColorSerie(0, Color.LIGHT_GRAY);
        graficoCPU.setColorSerie(1, Color.GREEN);
        graficoCPU.setIntervalo(1);
        graficoCPU.setDibujarespectrograma(true);
        graficoCPU.setValorMayor(100.0);//valor maximo de la serie
        graficoCPU.setMaximoTamanio(50);//maximo numero de muestras

        Accion accionCpu = new Accion() {
            @Override
            public void ejecutar(Object... parametros) {
                asociado.pedirCPUINFO();
            }
        };

        cargaCPU = new HiloAccion(accionCpu, 1000);
        tabPanCPU.addTab("CPU", graficoCPU);
    }

    private void configurarMonitorRAM() {
        graficoRAM = new PanelMonitorCarga(300, 50);
        graficoRAM.setOpaque(true); //content panes must be opaque
        graficoRAM.iniciarSeries(1);
        graficoRAM.setColorSerie(0, Color.CYAN);
        graficoRAM.setIntervalo(1);
        graficoRAM.setDibujarespectrograma(true);
        //maximo es el tamanio de la ram
        graficoRAM.setValorMayor(((com.sun.management.OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean()).getTotalPhysicalMemorySize());
        graficoRAM.setMaximoTamanio(50);//maximo numero de muestras

        Accion accionRam = new Accion() {
            @Override
            public void ejecutar(Object... parametros) {
                asociado.pedirRAMINFO();
            }
        };
        cargaRAM = new HiloAccion(accionRam, 1000);

        tabPanRAM.addTab("RAM", graficoRAM);
//        jPanel1.add(graficoRAM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tabPanCPU = new javax.swing.JTabbedPane();
        tabPanRAM = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CPU:");

        jLabel2.setText("RAM");

        jLabel3.setText("Proceso Java=  CPU=");

        jLabel4.setText("Libre= Ram= Ocupado=");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnIniciar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanCPU, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addComponent(tabPanRAM)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if (btnIniciar.isSelected()) {
            btnIniciar.setIcon(Util.cargarIcono16("/resources/stop_close.png"));
            btnIniciar.setText("Detener");
            Accion accionRam = new Accion() {
                @Override
                public void ejecutar(Object... parametros) {
                    asociado.pedirRAMINFO();
                }
            };
            cargaRAM = new HiloAccion(accionRam, 1000);
            Accion accionCpu = new Accion() {
                @Override
                public void ejecutar(Object... parametros) {
                    asociado.pedirCPUINFO();
                }
            };

            cargaCPU = new HiloAccion(accionCpu, 1000);
            cargaCPU.iniciar();
            cargaRAM.iniciar();
        } else {
            btnIniciar.setIcon(Util.cargarIcono16("/resources/start.png"));
            btnIniciar.setText("Iniciar");
            cargaCPU.detener();
            cargaRAM.detener();

            cargaRAM = null;
            cargaCPU = null;
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane tabPanCPU;
    private javax.swing.JTabbedPane tabPanRAM;
    // End of variables declaration//GEN-END:variables
}
