/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qooport;

import certificado.IniciarCertificado;
import comunes.Configuracion;
import qooport.avanzado.QoopoRT;
import qooport.gui.LookandFeelUtil;
import qooport.proxy.ModoProxy;
import qooport.simple.ModoSimple;
import qooport.utilidades.GC;
import qooport.utilidades.QoopoIMG;
import qooport.utilidades.SerializarUtil;
import qooport.utilidades.Util;

/**
 *
 * @author alberto
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicial
     */
    public Inicio() {
        IniciarCertificado.iniciar();
        QoopoIMG.iniciar();
        Global.extraerLibs();
        Global.extraerLibsDelServer();

        try {
            Configuracion config2 = (Configuracion) SerializarUtil.leerObjeto("config.dat");
            LookandFeelUtil.aplicarTema((String) config2.obtenerParametro("tema"));
            LookandFeelUtil.actualizar();
        } catch (Exception e) {
            LookandFeelUtil.aplicarTemaDefault();
        }
        initComponents();
        this.btnModoSimple.setIcon(Util.cargarIcono32("/resources/remote.png"));
        this.btnModoAvanzado.setIcon(Util.cargarIcono32("/resources/modo_avanzado.png"));
        this.btnProxy.setIcon(Util.cargarIcono32("/resources/proxy.png"));
        this.setIconImage(Util.cargarIcono16("/resources/remote.png").getImage());
        this.setLocationRelativeTo(null);
        lblTitulo.setIcon(Util.cargarIcono32("/resources/remote.png"));
        this.setTitle("QoopoRT");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModoSimple = new javax.swing.JButton();
        btnModoAvanzado = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnProxy = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnModoSimple.setText("MODO SIMPLE        ");
        btnModoSimple.setToolTipText("Este modo provee una interfaz intuitiva al mismo modo que TeamViewer. Permite recibir conexiones remotas e iniciar una conexión.");
        btnModoSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoSimpleActionPerformed(evt);
            }
        });

        btnModoAvanzado.setText("MODO AVANZADO");
        btnModoAvanzado.setToolTipText("Este modo es similiar al estandar de los RATs. Permite la creación de nuevos clientes que se conecten de fomra inversa.");
        btnModoAvanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoAvanzadoActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("QoopoRT");

        btnProxy.setText("MODO PROXY        ");
        btnProxy.setToolTipText("Este modo permite redirigir todas la conexiones a otro quipo");
        btnProxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(btnModoAvanzado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModoSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(btnProxy, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnModoAvanzado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProxy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModoSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoSimpleActionPerformed
        //cliente = new QoopoRT(false);
//        ModoSimple simple = new ModoSimple("Qoopo RT (Remote Tools)", cliente);
        ModoSimple simple = new ModoSimple("Qoopo RT (Remote Tools)");
        simple.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModoSimpleActionPerformed

    private void btnModoAvanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoAvanzadoActionPerformed
        QoopoRT.iniciar();
        this.dispose();
    }//GEN-LAST:event_btnModoAvanzadoActionPerformed

    private void btnProxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxyActionPerformed
        ModoProxy proxy = new ModoProxy("Qoopo RT (Remote Tools)");
        proxy.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProxyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        GC.iniciar();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModoAvanzado;
    private javax.swing.JButton btnModoSimple;
    private javax.swing.JButton btnProxy;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
