/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qooport.avanzado;

import comunes.Configuracion;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import qooport.gui.LookandFeelUtil;
import qooport.utilidades.SerializarUtil;
import qooport.utilidades.Util;
import qooport.utilidades.cifrado.Encriptacion;

/**
 *
 * @author aigarcia
 */
public class Config extends javax.swing.JFrame {

    private QoopoRT cliente;

    /**
     * Creates new form Config
     */
    public Config(QoopoRT cliente) {
        initComponents();
        this.cliente = cliente;

        Configuracion config2;

        cmbTemas.removeAllItems();
        try {
            config2 = (Configuracion) SerializarUtil.leerObjeto("config.dat");
        } catch (Exception ex) {
            config2 = new Configuracion();
        }

        for (String tema : LookandFeelUtil.getListaTemas()) {
            cmbTemas.addItem(tema);
        }

        try {
            cmbTemas.setSelectedItem((String) config2.obtenerParametro("tema"));
        } catch (Exception e) {
        }

        this.setTitle("Configuración");
        this.setIconImage(Util.cargarIcono16("/resources/advancedsettings.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        iniciarArranque = new javax.swing.JCheckBox();
        chkNotificar = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtRutaEquipos = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chkPedirArchivoOffline = new javax.swing.JCheckBox();
        chkActualizarserver = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtRutaArchivo = new javax.swing.JTextField();
        btnAbrirArchivo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        chkPedirInfo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIps = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbTemas = new javax.swing.JComboBox<>();
        btnAplicar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        iniciarArranque.setText("Iniciar QoopoRT al arranque");

        chkNotificar.setText("Mostrar nofiticación cuando se conecte un cliente");

        jLabel5.setText("Ruta de Equipos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRutaEquipos)
                    .addComponent(iniciarArranque, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNotificar)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(iniciarArranque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkNotificar)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRutaEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel3);

        jLabel1.setText("Ejecuta las siguientes acciones cuando un cliente se conecta");

        chkPedirArchivoOffline.setText("Pedir archivo de capturas offline");

        chkActualizarserver.setText("Actualizar servidor");

        jLabel2.setText("Servidor:");

        btnAbrirArchivo.setText("Buscar");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        jLabel3.setText("Versión:");

        txtVersion.setText("1.4.1");

        chkPedirInfo.setText("Pedir información sistema y guardar a archivo .txt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(chkPedirArchivoOffline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRutaArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbrirArchivo))
                    .addComponent(chkActualizarserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkPedirInfo))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPedirArchivoOffline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPedirInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkActualizarserver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrirArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Acciones al conectar", jPanel1);

        jLabel7.setText("Seguridad");

        jLabel8.setText("Password");

        jLabel9.setText("IPs Bloqueadas");
        jLabel9.setToolTipText("No permite la conexión de las ips. Debe escribir una en cada linea");

        txtPassword.setText("jPasswordField1");

        txtIps.setColumns(20);
        txtIps.setRows(5);
        jScrollPane1.setViewportView(txtIps);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Seguridad", jPanel2);

        jLabel4.setText("Tema:");

        cmbTemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAplicar.setText("Aplicar Tema");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTemas, 0, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAplicar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAplicar))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aspecto", jPanel4);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed

        JFileChooser cd = new JFileChooser();
        cd.setDialogType(JFileChooser.OPEN_DIALOG);
        cd.setFileFilter(new FileNameExtensionFilter("Seleccione servidor", new String[]{"jar"}));
        cd.setSelectedFile(new File("servidor"));
//                if (cd.showOpenDialog(this) == 0) {
        if (cd.showOpenDialog(null) == 0) {
            txtRutaArchivo.setText(cd.getSelectedFile().getAbsolutePath());
        }

    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed

        try {
            cliente.getConfig().agregarParametro("tema", cmbTemas.getSelectedItem().toString());
            SerializarUtil.escribirArchivo(cliente.getConfig(), "config.dat");

            LookandFeelUtil.aplicarTema(cmbTemas.getSelectedItem().toString());
            LookandFeelUtil.actualizar();

//                    System.out.println("tema es " + cmbTemas.getSelectedItem().toString());
//                    System.out.println("Intentando aplicar tema en caliente");
//                    Inicio.main(null);
//                    QoopoRT.instancia.detenerServicio();
//                    QoopoRT.instancia = null;
//                    ModoAvanzado.this.dispose();
            //LookandFeelUtil.aplicarTema(cmbTemas.getSelectedItem().toString());
            //ModoAvanzado.this.pack();
            //guardo la configuracion
        } catch (Exception ex) {
            Logger.getLogger(ModoAvanzado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {

            cliente.getConfig().setRutaArchivo(getTxtRutaArchivo().getText());
            cliente.getConfig().setVersion(getTxtVersion().getText());
            cliente.getConfig().setActualizarserver(getChkActualizarserver().isSelected());
            cliente.getConfig().setPedirArchivoOffline(getChkPedirArchivoOffline().isSelected());
            cliente.getConfig().agregarParametro("iniciarArranque", getIniciarArranque().isSelected());
            cliente.getConfig().agregarParametro("clave", Encriptacion.cifra(getTxtPassword().getText()));
            cliente.getConfig().agregarParametro("ipsbloqueadas", getTxtIps().getText());
            cliente.getConfig().agregarParametro("notificacion", getChkNotificar().isSelected());
            cliente.getConfig().agregarParametro("dirEquipos", txtRutaEquipos.getText());
            
            QoopoRT.MOSTRAR_NOTIFICACION = getChkNotificar().isSelected();

            SerializarUtil.escribirArchivo(cliente.getConfig(), "config.dat");
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkActualizarserver;
    private javax.swing.JCheckBox chkNotificar;
    private javax.swing.JCheckBox chkPedirArchivoOffline;
    private javax.swing.JCheckBox chkPedirInfo;
    private javax.swing.JComboBox<String> cmbTemas;
    private javax.swing.JCheckBox iniciarArranque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtIps;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtRutaArchivo;
    private javax.swing.JTextField txtRutaEquipos;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getChkActualizarserver() {
        return chkActualizarserver;
    }

    public void setChkActualizarserver(JCheckBox chkActualizarserver) {
        this.chkActualizarserver = chkActualizarserver;
    }

    public JCheckBox getChkPedirArchivoOffline() {
        return chkPedirArchivoOffline;
    }

    public void setChkPedirArchivoOffline(JCheckBox chkPedirArchivoOffline) {
        this.chkPedirArchivoOffline = chkPedirArchivoOffline;
    }

    public JCheckBox getIniciarArranque() {
        return iniciarArranque;
    }

    public void setIniciarArranque(JCheckBox iniciarArranque) {
        this.iniciarArranque = iniciarArranque;
    }

    public JTextArea getTxtIps() {
        return txtIps;
    }

    public void setTxtIps(JTextArea txtIps) {
        this.txtIps = txtIps;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public JTextField getTxtRutaArchivo() {
        return txtRutaArchivo;
    }

    public void setTxtRutaArchivo(JTextField txtRutaArchivo) {
        this.txtRutaArchivo = txtRutaArchivo;
    }

    public JTextField getTxtVersion() {
        return txtVersion;
    }

    public void setTxtVersion(JTextField txtVersion) {
        this.txtVersion = txtVersion;
    }

    public JCheckBox getChkNotificar() {
        return chkNotificar;
    }

    public void setChkNotificar(JCheckBox chkNotificar) {
        this.chkNotificar = chkNotificar;
    }

    public JCheckBox getChkPedirInfo() {
        return chkPedirInfo;
    }

    public void setChkPedirInfo(JCheckBox chkPedirInfo) {
        this.chkPedirInfo = chkPedirInfo;
    }

    public JTextField getTxtRutaEquipos() {
        return txtRutaEquipos;
    }

    public void setTxtRutaEquipos(JTextField txtRutaEquipos) {
        this.txtRutaEquipos = txtRutaEquipos;
    }

    
    
}
