/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qooport.avanzado;

import comunes.Accion;
import java.awt.Color;
import java.lang.management.ManagementFactory;
import qooport.gui.personalizado.PanelMonitorCarga;
import qooport.utilidades.Util;
import qooport.utilidades.monitorsistema.MonitorCargaCPU;
import qooport.utilidades.monitorsistema.MonitorCargaRAM;

/**
 *
 * @author aigarcia
 */
public class MonitorSistema extends javax.swing.JFrame {

    private static MonitorSistema instancia;
    private PanelMonitorCarga graficoCPU;
    private PanelMonitorCarga graficoRAM;

    private MonitorCargaCPU cargaCPU;
    private MonitorCargaRAM cargaRAM;

    /**
     * Creates new form MonitorSystema
     */
    public MonitorSistema() {
        initComponents();
//
        configurarMonitorCPU();
        configurarMonitorRAM();

        this.setIconImage(Util.cargarIcono16("/resources/monitor_load.png").getImage());

    }

    public static void ver() {
        if (instancia == null) {
            instancia = new MonitorSistema();
        }
        instancia.setVisible(true);
        instancia.pack();
    }

    private void configurarMonitorCPU() {
        graficoCPU = new PanelMonitorCarga(300, 50);
        graficoCPU.setOpaque(true); //content panes must be opaque
        graficoCPU.iniciarSeries(2);
        graficoCPU.setColorSerie(0, Color.BLUE);
        graficoCPU.setColorSerie(1, Color.GREEN);
        graficoCPU.setIntervalo(1);
        graficoCPU.setDibujarespectrograma(true);
        graficoCPU.setValorMayor(100.0);//valor maximo de la serie
        graficoCPU.setMaximoTamanio(200);//maximo numero de muestras
        Accion accion = new Accion() {
            @Override
            public void ejecutar(Object... parametros) {
                graficoCPU.agregarDato(0, (Double) parametros[0]);//system load
                graficoCPU.agregarDato(1, (Double) parametros[1]);//cpu load
                graficoCPU.repaint();
                jLabel3.setText("Proceso Java=" + Util.redondear((Double) parametros[0], 2) + "%  CPU=" + Util.redondear((Double) parametros[1], 2) + "%");
            }
        };

        cargaCPU = new MonitorCargaCPU(accion, 1000);
        cargaCPU.iniciar();
        tabPanCPU.addTab("CPU", graficoCPU);
    }

    private void configurarMonitorRAM() {
        graficoRAM = new PanelMonitorCarga(300, 50);
        graficoRAM.setOpaque(true); //content panes must be opaque
        graficoRAM.iniciarSeries(1);
        graficoRAM.setColorSerie(0, Color.CYAN);
        graficoRAM.setIntervalo(1);
        graficoRAM.setDibujarespectrograma(true);
        //maximo es el tamanio de la ram
        graficoRAM.setValorMayor(((com.sun.management.OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean()).getTotalPhysicalMemorySize());
        graficoRAM.setMaximoTamanio(200);//maximo numero de muestras

        Accion accion = new Accion() {
            @Override
            public void ejecutar(Object... parametros) {
                double ocupado = (Double) parametros[1] - (Double) parametros[0];//tamanio ram - ram libre
                graficoRAM.agregarDato(ocupado);
                graficoRAM.repaint();
                jLabel4.setText("RAM=" + Util.convertirBytes((Double) parametros[1]) + " Libre=" + Util.convertirBytes((Double) parametros[0]) + " Ocupado=" + Util.convertirBytes(ocupado));
            }
        };

        cargaRAM = new MonitorCargaRAM(accion, 1000);
        cargaRAM.iniciar();
        tabPanRAM.addTab("RAM", graficoRAM);
//        jPanel1.add(graficoRAM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tabPanCPU = new javax.swing.JTabbedPane();
        tabPanRAM = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CPU:");

        jLabel2.setText("RAM");

        jLabel3.setText("Proceso Java=  CPU=");

        jLabel4.setText("Libre= Ram= Ocupado=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanCPU, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addComponent(tabPanRAM)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MonitorSistema().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane tabPanCPU;
    private javax.swing.JTabbedPane tabPanRAM;
    // End of variables declaration//GEN-END:variables
}
