/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qooport.avanzado.crearcliente;

import javax.swing.JCheckBox;
import qooport.utilidades.Util;

/**
 *
 * @author alberto
 */
public class AntiVMPanel extends javax.swing.JPanel {

    /**
     * Creates new form conexion
     */
    public AntiVMPanel() {
        initComponents();

        lblTitulo.setIcon(Util.cargarIcono16("/resources/vmware.png"));

        this.antiVM_linux.setToolTipText("AÚN NO IMPLEMENTADO");
        this.antiVM_linux.setSelected(false);
        this.antiVM_linux.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        antiVM_windows = new javax.swing.JCheckBox();
        antiVM_linux = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTitulo.setText("Anti Virtual");

        jLabel3.setText("Evita la ejecución en entornos virtualizados para evitar análisis");

        antiVM_windows.setText("Windows (Pafish.exe 75 KB)");
        antiVM_windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiVM_windowsActionPerformed(evt);
            }
        });

        antiVM_linux.setText("Linux");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(antiVM_windows)
                            .addComponent(antiVM_linux))
                        .addGap(0, 347, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(antiVM_windows)
                .addGap(18, 18, 18)
                .addComponent(antiVM_linux)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void antiVM_windowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiVM_windowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antiVM_windowsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox antiVM_linux;
    private javax.swing.JCheckBox antiVM_windows;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getAntiVM_linux() {
        return antiVM_linux;
    }

    public void setAntiVM_linux(JCheckBox antiVM_linux) {
        this.antiVM_linux = antiVM_linux;
    }

    public JCheckBox getAntiVM_windows() {
        return antiVM_windows;
    }

    public void setAntiVM_windows(JCheckBox antiVM_windows) {
        this.antiVM_windows = antiVM_windows;
    }


}
