/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qooport.avanzado.crearcliente;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import static qooport.avanzado.QoopoRT.tipoLetra;
import qooport.utilidades.Util;

/**
 *
 * @author alberto
 */
public class InstalarPanel extends javax.swing.JPanel {

    /**
     * Creates new form conexion
     */
    public InstalarPanel() {
        initComponents();
        lblTitulo.setIcon(Util.cargarIcono16("/resources/puerto.png"));
        this.lblAutoInicio.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                autoInicioAP(evt);
            }
        });

        this.programadorTarea.setFont(new Font(tipoLetra, 1, 12));
        this.programadorTarea.setText("Programador de tareas.");
        this.programadorTarea.setEnabled(false);

        this.regName.setFont(new Font(tipoLetra, 1, 10));
        this.regName.setText("JavaUpdate");
                

//        this.comboTipoCarpeta.setModel(new DefaultComboBoxModel(new String[]{"Normal", "Papelera de reciclaje", "Modo Dios", "Personalización", "Juegos", "Administrar espacio de alamacenamiento"}));
        this.comboTipoCarpeta.setModel(new DefaultComboBoxModel(new String[]{"Normal"}));
    }

    public void autoInicioAP(ActionEvent evt) {
        if (this.lblAutoInicio.isSelected()) {
            this.autoinicio.setEnabled(true);
            this.servicio.setEnabled(true);
            this.programadorTarea.setEnabled(true);
            this.filename.setEnabled(true);
            this.regName.setEnabled(true);
            this.comboTipoCarpeta.setEnabled(true);
        } else {
            this.autoinicio.setEnabled(false);
            this.servicio.setEnabled(false);
            this.programadorTarea.setEnabled(false);

            this.filename.setEnabled(false);
            this.regName.setEnabled(false);

            this.comboTipoCarpeta.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAutoInicio = new javax.swing.JCheckBox();
        autoinicio = new javax.swing.JCheckBox();
        programadorTarea = new javax.swing.JCheckBox();
        servicio = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        regName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        filename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboTipoCarpeta = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTitulo.setText("Instalar");

        lblAutoInicio.setText("AutoInicio (Windows y Linux)");

        autoinicio.setText("Registro de Windows (HKLM/HKCU) o Autonicio Linux");

        programadorTarea.setText("Programador de tareas");

        servicio.setText("Instalar como servicio (Windows)");
        servicio.setToolTipText("Intenta instalar como servicio de windows. Esto da accesos de ADMINISTRADOR y se inicia antes de iniciar sesión");

        jLabel2.setText("Entrada Registro/Carpeta:");

        jLabel3.setText("Nombre del jar:");

        jLabel4.setText("Tipo de Carpeta:");

        comboTipoCarpeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Papelera" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAutoInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(servicio)
                                    .addComponent(programadorTarea)
                                    .addComponent(autoinicio))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(regName)
                                    .addComponent(filename)
                                    .addComponent(comboTipoCarpeta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAutoInicio)
                .addGap(18, 18, 18)
                .addComponent(autoinicio)
                .addGap(18, 18, 18)
                .addComponent(programadorTarea)
                .addGap(18, 18, 18)
                .addComponent(servicio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(regName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboTipoCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoinicio;
    private javax.swing.JComboBox<String> comboTipoCarpeta;
    private javax.swing.JTextField filename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox lblAutoInicio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JCheckBox programadorTarea;
    private javax.swing.JTextField regName;
    private javax.swing.JCheckBox servicio;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getAutoinicio() {
        return autoinicio;
    }

    public void setAutoinicio(JCheckBox autoinicio) {
        this.autoinicio = autoinicio;
    }

    public JComboBox<String> getComboTipoCarpeta() {
        return comboTipoCarpeta;
    }

    public void setComboTipoCarpeta(JComboBox<String> comboTipoCarpeta) {
        this.comboTipoCarpeta = comboTipoCarpeta;
    }

    public JTextField getFilename() {
        return filename;
    }

    public void setFilename(JTextField filename) {
        this.filename = filename;
    }

    public JTextField getRegName() {
        return regName;
    }

    public void setRegName(JTextField regName) {
        this.regName = regName;
    }

    public JCheckBox getLblAutoInicio() {
        return lblAutoInicio;
    }

    public void setLblAutoInicio(JCheckBox lblAutoInicio) {
        this.lblAutoInicio = lblAutoInicio;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public JCheckBox getProgramadorTarea() {
        return programadorTarea;
    }

    public void setProgramadorTarea(JCheckBox programadorTarea) {
        this.programadorTarea = programadorTarea;
    }

    public JCheckBox getServicio() {
        return servicio;
    }

    public void setServicio(JCheckBox servicio) {
        this.servicio = servicio;
    }

}
