/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qooport.avanzado.crearcliente;

import javax.swing.JCheckBox;
import qooport.utilidades.Util;

/**
 *
 * @author alberto
 */
public class PluginsPanel extends javax.swing.JPanel {

    /**
     * Creates new form conexion
     */
    public PluginsPanel() {
        initComponents();

        lblTitulo.setIcon(Util.cargarIcono16("/resources/plugin.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        adjuntarPluginsWebCam = new javax.swing.JCheckBox();
        adjuntarPluginsKeylogger = new javax.swing.JCheckBox();
        adjuntarPluginsJNA = new javax.swing.JCheckBox();
        adjuntarPluginsNirsoft = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTitulo.setText("Plugins");

        jLabel3.setText("Adjuntar plugins en el cliente. Aumenta su tamaño.");

        adjuntarPluginsWebCam.setText("Captura de cámara");
        adjuntarPluginsWebCam.setToolTipText("Permite la captura de la cámara");

        adjuntarPluginsKeylogger.setText("KeyLogger");
        adjuntarPluginsKeylogger.setToolTipText("Permite la captura de las pulsaciones del teclado. Para capturar el titulo de la ventana necesita JNA");

        adjuntarPluginsJNA.setText("JNA");
        adjuntarPluginsJNA.setToolTipText("Permite acceder a librerias nativas del sistema operativo. Ayuda al keylogger a obtener el título de la ventana. En windows ayuda a obtener el cursor actual. ");

        adjuntarPluginsNirsoft.setText("Nirsoft");
        adjuntarPluginsNirsoft.setToolTipText("Solo para windows. Utilidades nirsoft para obtener contraseñas. Puede ser detectado por el antivirus.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adjuntarPluginsNirsoft)
                            .addComponent(adjuntarPluginsWebCam)
                            .addComponent(adjuntarPluginsKeylogger)
                            .addComponent(adjuntarPluginsJNA))
                        .addGap(0, 394, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(adjuntarPluginsWebCam)
                .addGap(18, 18, 18)
                .addComponent(adjuntarPluginsKeylogger)
                .addGap(18, 18, 18)
                .addComponent(adjuntarPluginsJNA)
                .addGap(18, 18, 18)
                .addComponent(adjuntarPluginsNirsoft)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adjuntarPluginsJNA;
    private javax.swing.JCheckBox adjuntarPluginsKeylogger;
    private javax.swing.JCheckBox adjuntarPluginsNirsoft;
    private javax.swing.JCheckBox adjuntarPluginsWebCam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getAdjuntarPluginsJNA() {
        return adjuntarPluginsJNA;
    }

    public void setAdjuntarPluginsJNA(JCheckBox adjuntarPluginsJNA) {
        this.adjuntarPluginsJNA = adjuntarPluginsJNA;
    }

    public JCheckBox getAdjuntarPluginsKeylogger() {
        return adjuntarPluginsKeylogger;
    }

    public void setAdjuntarPluginsKeylogger(JCheckBox adjuntarPluginsKeylogger) {
        this.adjuntarPluginsKeylogger = adjuntarPluginsKeylogger;
    }

    public JCheckBox getAdjuntarPluginsNirsoft() {
        return adjuntarPluginsNirsoft;
    }

    public void setAdjuntarPluginsNirsoft(JCheckBox adjuntarPluginsNirsoft) {
        this.adjuntarPluginsNirsoft = adjuntarPluginsNirsoft;
    }

    public JCheckBox getAdjuntarPluginsWebCam() {
        return adjuntarPluginsWebCam;
    }

    public void setAdjuntarPluginsWebCam(JCheckBox adjuntarPluginsWebCam) {
        this.adjuntarPluginsWebCam = adjuntarPluginsWebCam;
    }

}
